### ISSUE TITLE
Bug in a TypeScript Project

### ISSUE THREAD

**Issue by YannickLeRoux** [danistefanovic/react-lazy-hero#11]
I am in the process of migrating my portfolio from a regular CRA application to a CRA-typescript app.

I am having issue with this LazyHero, as the background image is not displayed and this error pops up in the console: 

```
LazyHero.js:167 Uncaught TypeError: Cannot read property 'offsetHeight' of undefined
    at LazyHero.updateSize (LazyHero.js:167)
    at Image.image.onload (LazyHero.js:156)
```

I am new to TypeScript so it might be a problem with type declarations (maybe not). I just added a simple `declare module 'react-lazy-hero';` to have the app not crash, but might be not enough to have it work properly.
Any advice ?

**Comment by danistefanovic** [comment]
Would you be able to set up a reproduction repo? Thanks!

**Comment by YannickLeRoux** [comment]
of course,
https://github.com/YannickLeRoux/portfolio-typescript

Thank you

**Comment by YannickLeRoux** [comment]
I think I see where it is coming from : "styled-components.browser.esm.js:1979 The "innerRef" API has been removed in styled-components v4 in favor of React 16 ref forwarding, use "ref" instead like a typical component."
Do you want me to submit a PR ?

**Comment by danistefanovic** [comment]
Please try to downgrade to styled-components v3.

**Comment by danistefanovic** [comment]
`react-lazy-hero@2.0.0` should fix the issue.

**Comment by YannickLeRoux** [comment]
That was it thank you!

**Comment by danistefanovic** [comment]
Awesome!
