### ISSUE TITLE
Hero image not displaying

### ISSUE THREAD

**Issue by elliotpf** [danistefanovic/react-lazy-hero#12]
Hi,

It may seem simple and stupid but i'm at a dead end. 
Been staring at this for a long time...

I can't seem to get the image to display in the hero...
I've tried coping your example and still nothing...

![image](https://user-images.githubusercontent.com/36127202/49049559-646e1a00-f1d7-11e8-9e69-0bb26a6f68f3.png)
![image](https://user-images.githubusercontent.com/36127202/49049567-6cc65500-f1d7-11e8-9898-cbf2679e67d5.png)
![image](https://user-images.githubusercontent.com/36127202/49049585-810a5200-f1d7-11e8-939c-eeea8ca115a2.png)

Any assistance would be much appreciated.

 Regards,
Elliot

**Comment by danistefanovic** [comment]
~~Try to downgrade to styled-components v3.~~

**Comment by danistefanovic** [comment]
`react-lazy-hero@2.0.0` should fix the issue.

**Comment by elliotpf** [comment]
Can confirm that upgrading to latest version fixed it.
@danistefanovic  Thank you very much!

**Comment by danistefanovic** [comment]
Great!

**Comment by jared-dykstra** [comment]
Might want to leave this issue open until it's either fixed, or it's peer dependency is changed and pushed up to npm.
```
warning " > react-lazy-hero@2.0.0" has unmet peer dependency "styled-components@4.x".
```
Leaving the issue open would make it easier to find your suggestion to "install react-lazy-hero@2.0.0"

**Comment by danistefanovic** [comment]
The warning means that you should upgrade `styled-components` to v4 **in your project**.
