### ISSUE TITLE
Background image not rendereing from props

### ISSUE THREAD

**Issue by alluster** [danistefanovic/react-lazy-hero#3]
Hi, I'm having problems with rendering my BG in the lazy-hero!... can you help me figure ot the reason for this? Thank you!

This is how the browser looks:

![image](https://user-images.githubusercontent.com/21972091/35851608-348035cc-0b31-11e8-873b-25cad9f95fdb.png)
This is my index where I import my Hero.js:
![image](https://user-images.githubusercontent.com/21972091/35851636-487628e8-0b31-11e8-9fcd-c0e7dd4a4179.png)

In Hero.js I import lazy-hero
![image](https://user-images.githubusercontent.com/21972091/35851627-4070746e-0b31-11e8-93ec-c33c1151409b.png)

Do you have an idea about why the background-image: attribute doesn't show the picture?

**Comment by danistefanovic** [comment]
It looks like that the opacity is not switched from `0` to `1`. This happens if the image is not loaded or the hero component is not in the viewport. Are there any errors in the browser console?

**Comment by alluster** [comment]
There were warnings about the imageSrc={} supposed to be a string value in initial state in the parent component, which in my case was actually a boolean but changing this did not help. Also changed the opacity from string to a number due some warnings. Now when I console.log(heroImage) in the child component Hero.js right before it's supposed to throw it to the imageSrc={}, console shows that it renders empty few times. This is due my parent component gets the image from source later than the hero actually renders maybe? I'm not sure how to fix this..

**Comment by danistefanovic** [comment]
Can you test it with the newest version (react-lazy-hero@0.4.0)?

**Comment by alluster** [comment]
Great thanks, works like a charm now!

**Comment by MRMTC** [comment]
Hi @danistefanovic,


I am having a similar issue on my end with a react app that I created using "npx create-react-app".  My main "App.js" file consists of the following code segment:
`import React, { Component } from 'react';
//import './App.css';

import HeroImage from './components/HeroImage/HeroImage'

class App extends Component {
  render() {
    return (
      <div className="App2">

        <HeroImage />

        {/*<header className="App-header">
          <h1 className="App-title">Welcome to Boo \:D/</h1>
        </header>*/}

      </div>
    );
  }
}

export default App;`


The "HeroImage.js" file consist of the following piece of code:
`import React from 'react';
import LazyHero from 'react-lazy-hero';

const HeroImage = () => {

	return (
	        <div>
	            
	        	<link rel="stylesheet" href="bower_components/reset-css/reset.css" />

	            <LazyHero image="https://unsplash.it/2000/1000">
	                <h1>Generic Startup Hype Headline!</h1>
	            </LazyHero>

	            {/* ... */}
	        </div>
		)

}//end Hero

export default HeroImage;`

Looking at the console output in the Browser, there are no errors.  I tried using other image URLs, but I get the same result i.e. the page loads with no image.  I can however update the text.

When I inspect the element, I see that some of the styling elements are crossed out.  I have attached here an image at the end for your reference.  Can you please let me know what I am doing wrong?

Thanks.


![capture](https://user-images.githubusercontent.com/26508189/37245981-873f9a6e-24a9-11e8-9983-2fe72a9bcacc.PNG)
