### ISSUE TITLE
aria-labels

### ISSUE THREAD

**Issue by slinkardbrandon** [danistefanovic/react-lazy-hero#6]
Would you be able to add an optional attribute for the component that adds in aria-labels for accessibility?

**Comment by danistefanovic** [comment]
Isn't the `aria-label` attribute only applied to clickable elements?

**Comment by slinkardbrandon** [comment]
Oops my bad, I was overthinking the accessibility thing. Looks like generally speaking hero images shouldn’t even have alt text since they’re just for decorative purposes. Feel free to close the ticket!

**Comment by danistefanovic** [comment]
Thanks for the clarification.
